### ISSUE TITLE
Error on building website

### ISSUE THREAD

**Issue by agarwalrounak** [Cantera/cantera-website#57]
I was building the website using the steps mentioned [here](https://github.com/Cantera/cantera-website#to-build-the-website). I get the following error on executing the command `nikola auto -b`:
```
[2019-03-11T13:31:58Z] INFO: auto: Rebuilding the site...
Scanning posts..........done!
[2019-03-11T13:32:05Z] ERROR: Nikola: Error loading tasks. An unhandled exception occurred.
[2019-03-11T13:32:05Z] ERROR: Nikola: KeyError: 'electrochemistry'
[2019-03-11T13:32:05Z] NOTICE: Nikola: To see more details, run Nikola in debug mode (set environment variable NIKOLA_DEBUG=1) or use NIKOLA_SHOW_TRACEBACKS=1
Traceback (most recent call last):
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/nikola/plugin_categories.py", line 148, in execute
    return self._execute(options, args)
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/nikola/plugins/command/auto/__init__.py", line 215, in _execute
    self.wd_observer.start()
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 199, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/rounak/NumCantera/env/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 379, in _add_dir_watch
    raise OSError('Path is not a directory')
OSError: Path is not a directory
```
#### Python version
Python 3.6.3
#### Operating System
Ubuntu 17.10

### Note
Instead of cloning the original repositories, I was cloning the forked repositories though that should not make a difference

**Comment by bryanwweber** [comment]
This is because there is a new category of examples that was added to the Jupyter notebooks that we haven't handled on `master` yet. I have a fix for it coming with a bunch of other changes. In the meantime, you can edit [this dictionary](https://github.com/Cantera/cantera-website/blob/master/plugins/build_examples.py#L400) on your local copy (but please don't commit that change) to include an `electrochemistry` key that will fix this issue. However, see also #52 about `nikola auto -b`. The workaround for that is to do `nikola build && nikola serve -b`
