### ISSUE TITLE
UnicodeDecodeError on building website

### ISSUE THREAD

**Issue by agarwalrounak** [Cantera/cantera-website#61]
While executing the command `nikola build && nikola serve -b` to build the Cantera website, I got the UnicodeDecodeError twice
```
TaskError - taskid:process_ref_targets:pages\dave-goodwin.rst
PythonAction Error
Traceback (most recent call last):
  File "d:\gitpro\env\lib\site-packages\doit\action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "D:\GitPro\cantera-website\plugins\process_ref_targets.py", line 110, in process_targets
    data = in_file.read()
  File "d:\gitpro\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 3533: character maps to <undefined>

########################################
process_ref_targets:pages\dave-goodwin.rst <stdout>:
```
and 
```
TaskError - taskid:parse_docs:matlab
PythonAction Error
Traceback (most recent call last):
  File "d:\gitpro\env\lib\site-packages\doit\action.py", line 424, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "D:\GitPro\cantera-website\plugins\parse_docs.py", line 56, in process_targets
    tree = parse(html_file)
  File "d:\gitpro\env\lib\site-packages\lxml\html\__init__.py", line 939, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "src\lxml\etree.pyx", line 3435, in lxml.etree.parse
  File "src\lxml\parser.pxi", line 1861, in lxml.etree._parseDocument
  File "src\lxml\parser.pxi", line 1881, in lxml.etree._parseFilelikeDocument
  File "src\lxml\parser.pxi", line 1776, in lxml.etree._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 1187, in lxml.etree._BaseParser._parseDocFromFilelike
  File "src\lxml\parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 707, in lxml.etree._handleParseResult
  File "src\lxml\etree.pyx", line 314, in lxml.etree._ExceptionContext._raise_if_stored
  File "src\lxml\parser.pxi", line 370, in lxml.etree._FileReaderContext.copyToBuffer
  File "d:\gitpro\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2979: character maps to <undefined>

########################################
parse_docs:matlab <stdout>:
```

#### Operating System
Windows 10

### Note
I figured how to resolve the error and have the website succesfully running on my localhost. I will send a PR soon.

**Comment by bryanwweber** [comment]
What version of Python are you using?

**Comment by agarwalrounak** [comment]
Python 3.6.0
